config/routes.rb
Rails.application.routes.draw do
  resources :docs

  root 'welcome#index'

end

app/models/doc.rb
class Doc < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :find_doc, only: [:show, :edit, :update, :destroy]
  def index
    @docs=Doc.all
  end

  def show
  end

  def new
    @doc=Doc.new
  end

  def create
    @doc=Doc.new(doc_params)
    if @doc.save
      redirect_to docs_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if Doc.update
      redirect_to @doc
    else
      render 'edit'
    end
  end

  def destroy
    @doc.destroy
    redirect_to docs_path
  end

  private
    def find_doc
      @doc=Doc.find(params[:id])
    end

    def doc_params
      params.require(:doc).permit(:title, :content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/edit.html.erb
<h1>Edit this Doc</h1>
<%= form_for(@doc) do |f| %>
	
	<%= f.label :title %>
	<%= f.text_field :title %>

	<%= f.label :content %>
	<%= f.text_area :content %>

	<%= f.submit "Save", class: 'btn btn-success' %>

<% end %>
<%= link_to "Cancel", docs_path, class: 'btn btn-warning' %>

app/views/docs/index.html.erb
<h1>Index</h1>
<% unless @docs.blank? %>
	<% @docs.each do |d| %>
		<%= link_to doc_path(d) do %>
			<div class="well">
				<h1><%= d.title %></h1>
				<h3><%= time_ago_in_words(d.created_at) %></h3>
				<h3><%= truncate(d.content, length: 50) %></h3>
			</div>
		<% end %>
	<% end %>
	
<% else %>
	<div class="well">
		<p>You haven't created any documents yet. Go ahead and create a new document.</p>
	</div>
<% end %>
<%= link_to "Create a New Doc", new_doc_path, class: "btn btn-success" %>

app/views/docs/new.html.erb
<h1>Create a New Doc</h1>
<%= form_for(@doc) do |f| %>
	
	<%= f.label :title %>
	<%= f.text_field :title %>

	<%= f.label :content %>
	<%= f.text_area :content %>

	<%= f.submit "Create", class: 'btn btn-success' %>

<% end %>

<%= link_to "Cancel", docs_path, class: 'btn btn-warning' %>

app/views/docs/show.html.erb
<div class="well">
	<h1><%= @doc.title %></h1>
	<h3><%= @doc.content %></h3>
	<%= link_to 'Edit this Doc', edit_doc_path(@doc), class: 'btn btn-warning' %>
	<%= link_to "Delete", doc_path(@doc), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-danger' %>
</div>
<%= link_to "Index", docs_path, class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PracticeApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">

	<%= yield %>

</div>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome To My Practice App</h1>
<p>Docs</p>